// The datadog.yaml both agents read, and the core-check configs without which the core agent runs, reports
// healthy and collects nothing. Everything here is written under Harper's root, never the component directory.

import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join } from "node:path";
import { threadId } from "node:worker_threads";

// Rejects `rootPath: null`, which Harper's own defaultConfig.yaml ships, and anything relative: a relative
// root puts the runtime tree, the PID locks and the reaper's replacement-pid file under each worker's cwd.
const absoluteRoot = (value) => (value && isAbsolute(value) ? value : null);

// Read here rather than taken from an environment variable this package invents: Harper reads the same chain
// for itself and exposes no root path to a component. Absolute or null, never throws.
function readHarperRootPath() {
	try {
		const boot = readFileSync(
			join(homedir(), ".harperdb", "hdb_boot_properties.file"),
			"utf-8"
		);
		// Java-style properties, and Harper indents every line after the first, so the whitespace class matters.
		const settingsPath = boot.match(
			/^[ \t]*settings_path[ \t]*=[ \t]*(.+?)[ \t]*$/m
		)?.[1];
		if (!settingsPath) return null;
		// rootPath is top level in harper-config.yaml: the one key readable off a single line without a parser.
		const rootPath = readFileSync(settingsPath, "utf-8")
			.match(/^rootPath[ \t]*:[ \t]*(.+?)[ \t]*(?:#.*)?$/m)?.[1]
			?.replace(/^(['"])(.*)\1$/, "$2");
		return absoluteRoot(rootPath);
	} catch {
		return null;
	}
}

/** Harper's root path, or null. ROOTPATH is the harper-pro image's own spelling and wins where it is usable. */
function harperRoot(log) {
	const spelled = process.env.ROOTPATH;
	if (spelled && !absoluteRoot(spelled)) {
		log.warn(
			`Datadog supervisor: ROOTPATH="${spelled}" is not an absolute path, so it is ignored. A relative ` +
				`one resolves against each worker's own cwd, and two workers that disagree take different PID ` +
				`locks and each start their own pair of agents.`
		);
	}
	return absoluteRoot(spelled) ?? readHarperRootPath();
}

/** YAML-safe scalar; double quotes also survive Windows drive letters. */
const yamlString = (value) => JSON.stringify(String(value));

/** The datadog.yaml both agents read: every path off the unwritable Datadog defaults, and every port written as the value this component resolved, so the file the agents read and the ports this component probes can never be two different numbers. */
function renderDatadogYaml(paths, ports) {
	return [
		"# GENERATED by resources.js on every Harper worker start. Edits are overwritten.",
		"# api_key and site are absent by design: they ride in DD_API_KEY / DD_SITE, never on disk.",
		`confd_path: ${yamlString(paths.confd)}`,
		`run_path: ${yamlString(paths.run)}`,
		`auth_token_file_path: ${yamlString(paths.authToken)}`,
		`ipc_cert_file_path: ${yamlString(paths.ipcCert)}`,
		"# The agents log under the runtime tree; a stdio pipe would tie them to one worker thread.",
		"log_to_console: false",
		`log_file: ${yamlString(paths.coreLog)}`,
		// Both agents read these same top-level keys; apm_config has no rotation settings of its own.
		// 5 MiB by 2 rolls bounds each log file at 15 MiB, against a default that bounds nothing here.
		'log_file_max_size: "5Mb"',
		"log_file_max_rolls: 2",
		"# Loopback only. Nothing here should be reachable from outside the container.",
		'bind_host: "127.0.0.1"',
		"# Pinned because the core-agent verify reads expvar off this port.",
		`expvar_port: ${ports.expvar}`,
		"# Nothing here polls these two; they are written so DD_DOGSTATSD_PORT and DD_CMD_PORT are what the",
		"# agent binds. Unset, they are Datadog's own defaults, and a second copy on this host collides.",
		`dogstatsd_port: ${ports.dogstatsd}`,
		`cmd_port: ${ports.cmd}`,
		"apm_config:",
		"  enabled: true",
		`  receiver_port: ${ports.receiver}`,
		"  # On, this binds 0.0.0.0 and accepts spans from anything that reaches the container.",
		"  apm_non_local_traffic: false",
		`  log_file: ${yamlString(paths.traceLog)}`,
		"  # The trace-agent's own expvar, separate from the core agent's. Without it nothing on this node",
		"  # can say whether a span that reached the receiver ever left for Datadog.",
		"  debug:",
		`    port: ${ports.debug}`,
		"",
	].join("\n");
}

/** The shipped core checks that apply here; an optional `platforms` file beside a check gates it, absent means everywhere. */
function collectCoreChecks(packageConfd) {
	const checks = [];
	const entries = readdirSync(packageConfd, { withFileTypes: true }).sort(
		(a, b) => (a.name < b.name ? -1 : 1)
	);
	for (const entry of entries) {
		if (!entry.isDirectory() || !entry.name.endsWith(".d")) continue;
		const source = join(packageConfd, entry.name, "conf.yaml.default");
		if (!existsSync(source)) continue;
		const gate = join(packageConfd, entry.name, "platforms");
		if (existsSync(gate)) {
			const platforms = readFileSync(gate, "utf-8")
				.replace(/#.*$/gm, "")
				.split(/\s+/)
				.filter(Boolean);
			if (!platforms.includes(process.platform)) continue;
		}
		checks.push({
			dir: entry.name,
			name: entry.name.slice(0, -".d".length),
			body: readFileSync(source, "utf-8"),
		});
	}
	return checks;
}

/** This start owns exactly the conf.yaml.default files. One nobody claims was left by an older version on a persistent volume; an operator's own conf.yaml is never touched. */
function removeStaleDefaults(confd, owned) {
	for (const entry of readdirSync(confd, { withFileTypes: true })) {
		if (entry.isDirectory() && !owned.has(entry.name)) {
			rmSync(join(confd, entry.name, "conf.yaml.default"), { force: true });
		}
	}
}

// The runtime tree lives under Harper's root, never the component directory, which `harper deploy` replaces
// under a live agent. Named by the component's own directory, not just "datadog": sharing one pidDir means sharing one lock.
export function prepareRuntime(componentDir, { ports, log }) {
	const root = harperRoot(log);
	const runtimeDir = root
		? join(root, "datadog", basename(componentDir))
		: join(homedir(), ".harper-datadog", basename(componentDir));
	const paths = {
		runtimeDir,
		configFile: join(runtimeDir, "datadog.yaml"),
		confd: join(runtimeDir, "conf.d"),
		run: join(runtimeDir, "run"),
		authToken: join(runtimeDir, "run", "auth_token"),
		ipcCert: join(runtimeDir, "run", "ipc_cert.pem"),
		coreLog: join(runtimeDir, "logs", "agent.log"),
		traceLog: join(runtimeDir, "logs", "trace-agent.log"),
		// Not Harper's own pids/: the guard's reaper stops every guard-written lock it finds in the directory
		// it watches, and a shared one would hold locks this component never wrote.
		pidDir: join(runtimeDir, "pids"),
		reaperLog: join(runtimeDir, "logs", "reaper.log"),
	};
	mkdirSync(paths.run, { recursive: true });
	mkdirSync(dirname(paths.coreLog), { recursive: true });
	mkdirSync(paths.confd, { recursive: true });
	mkdirSync(paths.pidDir, { recursive: true });

	const configFiles = { [paths.configFile]: renderDatadogYaml(paths, ports) };
	let checks = [];
	try {
		checks = collectCoreChecks(join(componentDir, "conf.d"));
		for (const check of checks) {
			configFiles[join(paths.confd, check.dir, "conf.yaml.default")] =
				check.body;
		}
		removeStaleDefaults(paths.confd, new Set(checks.map((check) => check.dir)));
	} catch (error) {
		log.warn(
			`Datadog supervisor: no core check configuration was collected (${error.message}), so the agent ` +
				`will report healthy and collect no host metrics. Traces are unaffected.`
		);
	}

	return {
		root,
		paths,
		configFiles,
		coreChecks: checks.map((check) => check.name),
	};
}

/** Temp-and-rename, because every worker thread writes these and a rereading agent must see old or new, never torn. */
export function writeConfigFiles(configFiles, log) {
	for (const [target, contents] of Object.entries(configFiles)) {
		try {
			mkdirSync(dirname(target), { recursive: true });
			const temp = `${target}.${process.pid}.${threadId}.tmp`;
			writeFileSync(temp, contents, "utf-8");
			renameSync(temp, target);
		} catch (error) {
			log.error(
				`Datadog supervisor: could not write ${target}: ${error.message}`
			);
		}
	}
}
