// Every file the agents read, rendered.
//
// The datadog.yaml both agents read, the system-probe config all three read, security-agent's own, the log
// sources, and the core-check configs without which the core agent runs, reports healthy and collects
// nothing.
//
// Pure string production over its arguments. Nothing here resolves a path, reads an environment variable or
// polls anything, so a renderer cannot become a config file that depends on a running agent. Where a value
// is not derivable from the arguments - the reaper's service name, the ports - it arrives as one.

import { existsSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";

/**
 * Where the objects actually sit under the directory the probe package reports.
 *
 * The package ships `share/system-probe/`, and upstream's own default is
 * `${install_path}/embedded/share/system-probe/ebpf` (`pkg/config/setup/system_probe.go:128` at 7.82.1), so
 * `bpf_dir` names the `ebpf` child rather than its parent. Measured on a live container 2026-09-10: pointed
 * at the parent, system-probe finds no CO-RE object, falls through to runtime compilation, and fails with
 * `unable to find kernel headers`. It is a one-segment error that reads as a missing toolchain.
 */
const objectDir = (ebpfDir) => `${ebpfDir}/ebpf`;

/** The minimised BTF bundle shipped beside the objects, for kernels that publish none of their own. */
const btfBundle = (ebpfDir) => `${objectDir(ebpfDir)}/co-re/btf`;

/**
 * The system-probe.yaml every agent on this node reads.
 *
 * Written whether or not system-probe runs. Off, it is the file that stops the core agent asking a socket
 * nothing serves; on, it is where the socket, the log and the precompiled eBPF objects are named. One file
 * either way, because two would let the running config and the silencing config disagree.
 *
 * `bpf_dir` is the part that cannot be defaulted. The objects ship in the probe platform package rather than
 * at /opt/datadog-agent, so system-probe has to be told where they landed or it starts, answers `version`,
 * and loads not one program.
 *
 * `allow_prebuilt_fallback` has to be set for the same reason, and its default is the trap. Upstream
 * defaults it to false (`system_probe.go:138`), so a kernel that cannot do CO-RE loads nothing and the
 * prebuilt objects this package went to the trouble of extracting, verifying and shipping are dead weight
 * on disk. Shipping 42 MB that can never be read is worse than not shipping it, because the size says the
 * capability is there.
 */
export function renderSystemProbeYaml(paths, resolved, ebpfDir) {
	const yes = (value) => (value ? "true" : "false");
	const quote = (value) => JSON.stringify(String(value));
	return [
		"# GENERATED by resources.js on every Harper worker start. Edits are overwritten.",
		"# Read by system-probe (-c), by security-agent (--sysprobe-config) and by the core agent",
		"# (--sysprobecfgpath), so all three agree on the socket and on which modules exist.",
		"system_probe_config:",
		`  enabled: ${yes(resolved.systemProbe)}`,
		`  sysprobe_socket: ${quote(paths.sysprobeSocket)}`,
		...(ebpfDir
			? [
					"  # Where the probe platform package put Datadog's precompiled objects. Without this",
					"  # system-probe looks under /opt/datadog-agent, finds nothing, and loads no program.",
					`  bpf_dir: ${quote(objectDir(ebpfDir))}`,
					"  # The minimised BTF bundle shipped beside them. The kernel's own /sys/kernel/btf/vmlinux",
					"  # is used where it exists; this is what carries a kernel that publishes none.",
					`  btf_path: ${quote(btfBundle(ebpfDir))}`,
					"  # Without this the prebuilt objects are never loaded, whatever bpf_dir says: upstream",
					"  # defaults it off, and CO-RE or runtime compilation are then the only paths. Runtime",
					"  # compilation needs kernel headers a container does not have, so on a kernel where CO-RE",
					"  # does not apply the shipped objects are the only thing that works.",
					"  allow_prebuilt_fallback: true",
				]
			: []),
		"log_to_console: false",
		`log_file: ${quote(paths.sysprobeLog)}`,
		'log_file_max_size: "5Mb"',
		"log_file_max_rolls: 2",
		"# The core agent's workloadmeta collector reads this key from THIS file, not from datadog.yaml.",
		"# Off, it stops polling a socket nothing serves, which is the once-a-minute ERROR a node with no",
		"# system-probe reports. On, it is what service discovery runs through.",
		"discovery:",
		`  enabled: ${yes(resolved.modules.discovery)}`,
		"# Network Performance Monitoring: every connection on the host. Off by default here and in Datadog's",
		"# own config; DD_NETWORK_CONFIG_ENABLED=true turns it on.",
		"network_config:",
		`  enabled: ${yes(resolved.modules.networkMonitoring)}`,
		"# Universal Service Monitoring: protocol parsing on those connections.",
		"service_monitoring_config:",
		`  enabled: ${yes(resolved.modules.serviceMonitoring)}`,
		"runtime_security_config:",
		`  enabled: ${yes(resolved.security)}`,
		`  socket: ${quote(paths.securitySocket)}`,
		"  # The stock path is /etc/datadog-agent/runtime-security.d, which the harperdb user cannot",
		"  # create, so an enabled engine logs `error while loading policies` on every start.",
		"  policies:",
		`    dir: ${quote(paths.securityPolicies)}`,
		"",
	].join("\n");
}

/**
 * The security-agent's own config file.
 *
 * Separate from datadog.yaml because security-agent's `-c` takes its own list and a node that runs it wants
 * its log somewhere other than the core agent's. Everything else it needs it reads from the system-probe
 * config it is pointed at.
 */
export function renderSecurityAgentYaml(paths, resolved) {
	const quote = (value) => JSON.stringify(String(value));
	return [
		"# GENERATED by resources.js on every Harper worker start. Edits are overwritten.",
		"log_to_console: false",
		`log_file: ${quote(paths.securityLog)}`,
		'log_file_max_size: "5Mb"',
		"log_file_max_rolls: 2",
		"runtime_security_config:",
		`  enabled: ${resolved.security ? "true" : "false"}`,
		`  socket: ${quote(paths.securitySocket)}`,
		"  policies:",
		`    dir: ${quote(paths.securityPolicies)}`,
		"# Off unless asked for: CSPM scans the host's configuration and is a separate product from runtime",
		"# security. DD_COMPLIANCE_CONFIG_ENABLED=true turns it on, and the environment outranks this file.",
		"compliance_config:",
		"  enabled: false",
		"",
	].join("\n");
}

/** YAML-safe scalar; double quotes also survive Windows drive letters. */
const yamlString = (value) => JSON.stringify(String(value));

/** The datadog.yaml both agents read: every path off the unwritable Datadog defaults, and the three ports this component probes written as the values it resolved, so a change to an agent default cannot move a port out from under a probe. */
export function renderDatadogYaml(paths, ports) {
	return [
		"# GENERATED by resources.js on every Harper worker start. Edits are overwritten.",
		"# api_key and site are absent by design: they ride in DD_API_KEY / DD_SITE, never on disk.",
		"# The component's own settings are not here either, because the agent does not read them. They are",
		"# DD_HARPER_PROCESS_METRICS_ENABLED / _INTERVAL / _INCLUDE / _EXCLUDE, and the resolved values are",
		"# reported by the DatadogStatus endpoint under `processMetrics`.",
		`confd_path: ${yamlString(paths.confd)}`,
		`run_path: ${yamlString(paths.run)}`,
		`auth_token_file_path: ${yamlString(paths.authToken)}`,
		`ipc_cert_file_path: ${yamlString(paths.ipcCert)}`,
		"# The agents log under the runtime tree; a stdio pipe would tie them to one worker thread.",
		"log_to_console: false",
		`log_file: ${yamlString(paths.coreLog)}`,
		// Both agents read these same top-level keys; apm_config has no rotation settings of its own.
		// 5 MiB by 2 rolls bounds each log file at 15 MiB, against a default that bounds nothing here.
		'log_file_max_size: "5Mb"',
		"log_file_max_rolls: 2",
		"# Loopback only. Nothing here should be reachable from outside the container.",
		'bind_host: "127.0.0.1"',
		"# Empty, so the agent does not try to bind a Unix socket at /var/run/datadog/, which is the stock",
		"# install's path and does not exist beside a component. Measured on 7.82.1: unset, every start logs",
		"# `Can't init UDS listener` at ERROR, which now reaches whoever reads this node's logs. DogStatsD",
		"# still listens on UDP, which is the port a tracer's runtime metrics use.",
		'dogstatsd_socket: ""',
		"# Pinned because this component sends its own per-process series here. Unpinned, the sender",
		"# reads the port from DD_DOGSTATSD_PORT or 8125 and the agent reads it from its own default, and a",
		"# change to that default would drop the series on the floor with nothing logged on either side.",
		`dogstatsd_port: ${ports.dogstatsd}`,
		"# The logs agent keeps its tail-offset registry, and the integrations launcher its spool, under this",
		"# path rather than the top-level run_path. Measured on 7.82.1: unset, every start logs `Unable to",
		"# create integrations logs directory: mkdir /opt/datadog-agent: permission denied` at ERROR, 57 of them",
		"# over a day's restarts, and the registry has nowhere to live, so a restarted node re-tails every log",
		"# from the beginning instead of resuming.",
		"logs_config:",
		`  run_path: ${yamlString(paths.run)}`,
		"# Pinned because the core-agent verify reads expvar off this port. Measured on 7.82.1: the environment",
		"# outranks this file, so a set DD_EXPVAR_PORT wins and this only pins the port against a default that moves.",
		`expvar_port: ${ports.expvar}`,
		"# Live Processes: every process on the node with its CPU, memory and command line, Harper and the agents",
		"# included. Go, so it runs in this Python-free build; DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=false",
		"# turns it off, since the environment outranks this file.",
		"process_config:",
		"  process_collection:",
		"    enabled: true",
		"  # process-agent's own expvar and log, which the core agent ignores and process-agent reads from",
		"  # this same file. Pinned for the same reason as the others: a probe reads the port this resolved.",
		`  expvar_port: ${ports.processExpvar}`,
		`  log_file: ${yamlString(paths.processLog)}`,
		"apm_config:",
		"  enabled: true",
		`  receiver_port: ${ports.receiver}`,
		"  # On, this binds 0.0.0.0 and accepts spans from anything that reaches the container.",
		"  apm_non_local_traffic: false",
		"  # Empty for the same reason as dogstatsd_socket: /var/run/datadog/ is the stock install's path and",
		"  # does not exist beside a component. Measured on 7.82.1: unset, every start logs `Could not start UDS",
		"  # listener: socket directory does not exist` at ERROR and the socket never binds. The receiver a",
		"  # tracer dials is the TCP port above.",
		'  receiver_socket: ""',
		`  log_file: ${yamlString(paths.traceLog)}`,
		"  # The sampler keeps this many traces a second per service and drops the rest. The default of 10",
		"  # was discarding 58% of a 24-trace-per-second demo whose whole purpose is showing traces, so a",
		"  # node that wants every span sets it above its own rate rather than discovering the loss in a",
		"  # sample-rate column. The key is target_traces_per_second: `target_tps` is the agent's internal",
		"  # field name and is silently ignored, and max_traces_per_second is deprecated in its favour.",
		"  # DD_APM_TARGET_TRACES_PER_SECOND overrides it; the environment outranks this file.",
		`  target_traces_per_second: ${TARGET_TPS}`,
		"  # The trace-agent's own expvar, separate from the core agent's. Without it nothing on this node",
		"  # can say whether a span that reached the receiver ever left for Datadog.",
		"  debug:",
		`    port: ${ports.debug}`,
		"",
	].join("\n");
}

/** Traces a second the sampler keeps per service. 10 is the agent's default and is below a busy demo. */
const TARGET_TPS = 200;

export const HARPER_LOG_CHECK = "harper.d";

/**
 * Log sources for what runs on this node: every log Harper writes under its log directory (`logging.root`
 * is `log` under the root path unless a node moved it; the HTTP request log `http.logging` enables lands
 * there too, under its own name), and the two agents' and the reaper's, which are the first thing an
 * operator wants when the node stops reporting. Tailed only while logs are enabled (DD_LOGS_ENABLED=true).
 *
 * `reaperName` arrives rather than being imported: it is the name a component chose for its own reaper lock,
 * and a renderer that reached back for it would be the one import making this file depend on its caller.
 */
export function renderLogSources(harperLog, paths, reaperName) {
	const source = (path, service, source) => [
		"  - type: file",
		`    path: ${yamlString(path)}`,
		`    service: ${service}`,
		`    source: ${source}`,
	];
	return [
		"# GENERATED by resources.js on every Harper worker start. Edits are overwritten.",
		"# Tailed only while logs are enabled (DD_LOGS_ENABLED=true).",
		"logs:",
		...source(join(dirname(harperLog), "*.log"), "harper", "harper"),
		...source(paths.coreLog, "datadog-agent", "datadog-agent"),
		...source(paths.traceLog, "datadog-trace-agent", "datadog-agent"),
		// Tailed by path, whether or not the file exists yet: the logs agent picks one up when it appears,
		// so a node that turns system-probe on later needs no config change to see its log.
		...source(paths.sysprobeLog, "datadog-system-probe", "datadog-agent"),
		...source(paths.processLog, "datadog-process-agent", "datadog-agent"),
		...source(paths.securityLog, "datadog-security-agent", "datadog-agent"),
		...source(paths.reaperLog, reaperName, "harper-process-guard"),
		"",
	].join("\n");
}

/** The shipped core checks that apply here; an optional `platforms` file beside a check gates it, absent means everywhere. */
export function collectCoreChecks(packageConfd) {
	const checks = [];
	const entries = readdirSync(packageConfd, { withFileTypes: true }).sort(
		(a, b) => (a.name < b.name ? -1 : 1)
	);
	for (const entry of entries) {
		if (!entry.isDirectory() || !entry.name.endsWith(".d")) continue;
		const source = join(packageConfd, entry.name, "conf.yaml.default");
		if (!existsSync(source)) continue;
		const gate = join(packageConfd, entry.name, "platforms");
		if (existsSync(gate)) {
			const platforms = readFileSync(gate, "utf-8")
				.replace(/#.*$/gm, "")
				.split(/\s+/)
				.filter(Boolean);
			if (!platforms.includes(process.platform)) continue;
		}
		checks.push({
			dir: entry.name,
			name: entry.name.slice(0, -".d".length),
			body: readFileSync(source, "utf-8"),
		});
	}
	return checks;
}

/** This start owns exactly the conf.yaml.default files. One nobody claims was left by an older version on a persistent volume; an operator's own conf.yaml is never touched. */
export function removeStaleDefaults(confd, owned) {
	for (const entry of readdirSync(confd, { withFileTypes: true })) {
		if (entry.isDirectory() && !owned.has(entry.name)) {
			rmSync(join(confd, entry.name, "conf.yaml.default"), { force: true });
		}
	}
}
